export enum LocalName {
    Articles = "Articles",
    Apports = "Apports",
    Budget = "Budget",
    Courses = "Courses",
    CourseDetails = "CourseDetails",
    Depenses = "Depenses",
    Epargnes = "Epargnes",
    Finances = "Finances",
    InfoConnexion = "InfoConnexion",
    Familles = "Familles",
    Groupes = "Groupes",
    Logs = "Logs",
    Magasins = "Magasins",
    Menus = "Menus",
    Plats = "Plats",
    PlatDetails = "PlatDetails",
    Utilisateurs = "Utilisateurs",
    Memos = "Memos",
    HistoriquePrix = "HistoriquePrix",
}